TravelAgency/TravelAgency/Controllers/ArrangementController.cs
using MongoDB.Bson;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelAgency.DataLayer.BusienssLogic;
using TravelAgency.DataLayer.Config;
using TravelAgency.DataLayer.Model;
using TravelAgency.DataLayer.Utilities;
using TravelAgency.ViewModels;

namespace TravelAgency.Controllers
{
    public class ArrangementController : Controller
    {
        // GET: Arrangement
        public ActionResult Index(String arrangementId, bool isLogged)
        {
            BusinessLogic logic = new BusinessLogic();
            MainPageViewModel model = new MainPageViewModel();
			model.IsLogged = isLogged;

            model.Destinations = logic.GetDestinations();

            List<Arrangement> topArrangements = logic.TopArrangements();
            foreach (var topArrangement in topArrangements)
            {
                ArrangementDestinationViewModel arrangement = new ArrangementDestinationViewModel();
                arrangement.Arrangement = topArrangement;
                arrangement.Destination = logic.GetArrangementDestination(topArrangement);
                model.TopArrangements.Add(arrangement);
            }

            model.Arrangement.Arrangement = logic.GetArrangemetById(arrangementId);
            model.Arrangement.Destination = logic.GetArrangementDestination(model.Arrangement.Arrangement);


            return View(model);
            
        }

        [HttpPost]
        public ActionResult Reservation(MainPageViewModel model, bool isLogged)
        {
            BusinessLogic logic = new BusinessLogic();
            Customer customer = model.Customer;

            logic.CreateCustomer(customer);
		  
            //in order to get id from database
            customer = logic.GetCustomerByPassportNumber(customer.PassportNumber);

            List<FellowTraveler> company = new List<FellowTraveler>();
            foreach(FellowTraveler traveler in model.Reservation.Company)
            {
                if (traveler.FirstName != null)
                    company.Add(traveler);
            }

            Reservation reservation = new Reservation
            {
                Customer = new MongoDB.Driver.MongoDBRef(CollectionsNames.CustomersCollection, customer.Id),
                Arrangement = new MongoDB.Driver.MongoDBRef(CollectionsNames.ArrangementsCollection, new ObjectId(model.Arrangement.Arrangement.Description)), //HACK: ne moze da se namapira ObjectId kao string..
                Company = company
            };

            logic.CreateReservation(reservation);

			return RedirectToAction("LoggedIndex", "Main", new { isLogged = isLogged });
		}
    }
}

TravelAgency/TravelAgency/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelAgency.DataLayer.BusienssLogic;
using TravelAgency.DataLayer.Model;
using TravelAgency.DataLayer.Utilities;
using TravelAgency.ViewModels;

namespace TravelAgency.Controllers
{
    public class MainController : Controller
    {
        // GET: Main
        public ActionResult Index()
        {
			BusinessLogic logic = new BusinessLogic();
			MainPageViewModel model = new MainPageViewModel();
			model.Destinations = logic.GetFirstNDestinations(7);
            model.Countries = logic.GetCountries(10);

			List<Arrangement> topArrangements = logic.TopArrangements();			

			foreach (var topArrangement in topArrangements)
			{
				ArrangementDestinationViewModel arrangement = new ArrangementDestinationViewModel();
				arrangement.Arrangement = topArrangement;
				arrangement.Destination = logic.GetArrangementDestination(topArrangement);
				model.TopArrangements.Add(arrangement);
			}

            return View(model);
        }

		public ActionResult LoggedIndex(bool isLogged)
		{
			BusinessLogic logic = new BusinessLogic();
			MainPageViewModel model = new MainPageViewModel();
			model.Destinations = logic.GetFirstNDestinations(7);
			model.Countries = logic.GetCountries(10);
			model.IsLogged = isLogged;

			List<Arrangement> topArrangements = logic.TopArrangements();

			foreach (var topArrangement in topArrangements)
			{
				ArrangementDestinationViewModel arrangement = new ArrangementDestinationViewModel();
				arrangement.Arrangement = topArrangement;
				arrangement.Destination = logic.GetArrangementDestination(topArrangement);
				model.TopArrangements.Add(arrangement);
			}

			return View(model);
		}

		public ActionResult SearchDestinations(string criteria, bool isLogged)
		{
			BusinessLogic logic = new BusinessLogic();
			MainPageViewModel model = new MainPageViewModel();

			model.Destinations = logic.GetDestinations();
			model.SearchedDestinations = logic.SearchDestinations(criteria);
			model.IsLogged = isLogged;

			List<Arrangement> topArrangements = logic.TopArrangements();

			foreach (var topArrangement in topArrangements)
			{
				ArrangementDestinationViewModel arrangement = new ArrangementDestinationViewModel();
				arrangement.Arrangement = topArrangement;
				arrangement.Destination = logic.GetArrangementDestination(topArrangement);
				model.TopArrangements.Add(arrangement);
			}

			return View(model);
		}

        public ActionResult CountryArrangements(String country, bool isLogged)
        {
            BusinessLogic logic = new BusinessLogic();
            MainPageViewModel model = new MainPageViewModel();

            model.Destinations = logic.GetDestinations();
			model.IsLogged = isLogged;

            List<Arrangement> topArrangements = logic.TopArrangements();
            foreach (var topArrangement in topArrangements)
            {
                ArrangementDestinationViewModel arrangement = new ArrangementDestinationViewModel();
                arrangement.Arrangement = topArrangement;
                arrangement.Destination = logic.GetArrangementDestination(topArrangement);
                model.TopArrangements.Add(arrangement);
            }

            List<Arrangement> arrangements = logic.GetArrangementsForDestination(country);
            foreach (var arrangement in arrangements)
            {
                ArrangementDestinationViewModel arrangementVM = new ArrangementDestinationViewModel();
                arrangementVM.Arrangement = arrangement;
                arrangementVM.Destination = logic.GetArrangementDestination(arrangement);
                model.Arrangements.Add(arrangementVM);
            }

			SearchArrangements searchArrangements = new SearchArrangements()
			{
				Country = country
			};

			List<Arrangement> searchedArrangements = logic.SearchArrangements(searchArrangements);
			foreach (var searched in searchedArrangements)
			{
				ArrangementDestinationViewModel arrangement = new ArrangementDestinationViewModel();
				arrangement.Arrangement = searched;
				arrangement.Destination = logic.GetArrangementDestination(searched);
				model.SearchedArrangements.Add(arrangement);
			}

			return View("Arrangements", model);
        }

        public ActionResult PlaceArrangements(string placeName, bool isLogged)
        {
			BusinessLogic logic = new BusinessLogic();
			MainPageViewModel model = new MainPageViewModel();
			SearchArrangements criteria = new SearchArrangements()
			{				
				PlaceName = placeName
			};

			model.IsLogged = isLogged;
			model.Destinations = logic.GetFirstNDestinations(7);
			List<Arrangement> searchedArrangements = new List<Arrangement>();
			searchedArrangements = logic.SearchArrangements(criteria);
			List<Arrangement> topArrangements = logic.TopArrangements();

			foreach (var topArrangement in topArrangements)
			{
				ArrangementDestinationViewModel arrangement = new ArrangementDestinationViewModel();
				arrangement.Arrangement = topArrangement;
				arrangement.Destination = logic.GetArrangementDestination(topArrangement);
				model.TopArrangements.Add(arrangement);
			}

			foreach (var searched in searchedArrangements)
			{
				ArrangementDestinationViewModel arrangement = new ArrangementDestinationViewModel();
				arrangement.Arrangement = searched;
				arrangement.Destination = logic.GetArrangementDestination(searched);
				model.SearchedArrangements.Add(arrangement);
			}

			return View(model);
        }

		public ActionResult AdvanceSearch(MainPageViewModel criteria)
		{
			BusinessLogic logic = new BusinessLogic();
			MainPageViewModel model = new MainPageViewModel();			

			model.Destinations = logic.GetFirstNDestinations(7);
			List<Arrangement> searchedArrangements = logic.SearchArrangements(criteria.SearchCriterias);
			List<Arrangement> topArrangements = logic.TopArrangements();

			foreach (var topArrangement in topArrangements)
			{
				ArrangementDestinationViewModel arrangement = new ArrangementDestinationViewModel();
				arrangement.Arrangement = topArrangement;
				arrangement.Destination = logic.GetArrangementDestination(topArrangement);
				model.TopArrangements.Add(arrangement);
			}

			foreach (var searched in searchedArrangements)
			{
				ArrangementDestinationViewModel arrangement = new ArrangementDestinationViewModel();
				arrangement.Arrangement = searched;
				arrangement.Destination = logic.GetArrangementDestination(searched);
				model.SearchedArrangements.Add(arrangement);
			}

			return View(model);
		}
    }
}

TravelAgency/TravelAgency/Views/Main/AdvanceSearch.cshtml
@{
    ViewBag.Title = "Aranžmani";
    Layout = "~/Views/Shared/_HomePageLayout.cshtml";
}

<h2>Aranžmani</h2>

@foreach (var arrangement in Model.SearchedArrangements)
{
    <div class="single_stuff wow fadeInDown">
        <div class="single_stuff_img"> <a href="#"><img src="~/images/stuff_img1.jpg" alt=""></a> </div>
        <div class="single_stuff_article">
            <div class="single_sarticle_inner">
                <a class="stuff_category" href="#">@arrangement.Destination.Country</a>
                <div class="stuff_article_inner">
                    <span class="stuff_date"><strong>@String.Format("{0:dd MMM}", arrangement.Arrangement.StartDate)</strong></span>
                    <h2><a href="#">@arrangement.Destination.PlaceName</a></h2>
                    <p>Cena: @arrangement.Arrangement.Price</p>
                </div>
            </div>
        </div>
    </div>
}

TravelAgency/TravelAgency/Views/Main/Arrangements.cshtml
@model TravelAgency.ViewModels.MainPageViewModel

@{
    ViewBag.Title = "Aranžmani";
    Layout = "~/Views/Shared/_HomePageLayout.cshtml";
}

<h2>Aranzmani</h2>


@foreach (var arrangement in Model.Arrangements)
{
    <div class="single_stuff wow fadeInDown">
        <div class="single_stuff_img"> <a href="#"><img src="~/images/stuff_img1.jpg" alt=""></a> </div>
        <div class="single_stuff_article">
            <div class="single_sarticle_inner">
                <a class="stuff_category" href="#">@arrangement.Destination.Country</a>
                <div class="stuff_article_inner">
                    <span class="stuff_date"><strong>@String.Format("{0:dd MMM}", arrangement.Arrangement.StartDate)</strong></span>
                    <h2>
                        @{ 
                            String place = arrangement.Destination.PlaceName != null ? arrangement.Destination.PlaceName : " ";
                            String arrangementId = arrangement.Arrangement.Id.ToString();
                        }
                        @Html.ActionLink(place, "Index", "Arrangement", new { arrangementId = arrangementId, isLogged = Model.IsLogged }, null)
                    </h2>
                    <p>Cena: @arrangement.Arrangement.Price</p>
                </div>
            </div>
        </div>
    </div>
}

TravelAgency/TravelAgency/Views/Main/Index.cshtml
@model TravelAgency.ViewModels.MainPageViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_HomePageLayout.cshtml";
}


<h2>Zemlje u ponudi</h2>


@foreach (var destination in Model.Countries)
{
    <div class="single_stuff wow fadeInDown">
        <div class="single_stuff_img"> <a href="pages/single.html"><img src="~/images/stuff_img1.jpg" alt=""></a> </div>
        <div class="single_stuff_article">
            <div class="single_sarticle_inner">
                <div class="stuff_article_inner">
                    <h2>
                        @{  string text = destination.Country != null ? destination.Country : " ";
                        }
                        @Html.ActionLink(text, "CountryArrangements", "Main",new { country = destination.Country, isLogged = Model.IsLogged }, null)
                    </h2>
                    <p>@destination.Description</p>
                </div>
            </div>
        </div>
    </div>
}


            

TravelAgency/TravelAgency/Views/Main/LoggedIndex.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_HomePageLayout.cshtml";
}

<h2>U ponudi</h2>

@foreach (var destination in Model.Countries)
{
    <div class="single_stuff wow fadeInDown">
        <div class="single_stuff_img"> <a href="pages/single.html"><img src="~/images/stuff_img1.jpg" alt=""></a> </div>
        <div class="single_stuff_article">
            <div class="single_sarticle_inner">
                <div class="stuff_article_inner">
                    <h2>
                        @{  string text = destination.Country != null ? destination.Country : " ";
                        }
                        @Html.ActionLink(text, "CountryArrangements", "Main", new { country = destination.Country, isLogged = Model.IsLogged }, null)
                    </h2>
                    <p>@destination.Description</p>
                </div>
            </div>
        </div>
    </div>
                            }

TravelAgency/TravelAgency/Views/Main/PlaceArrangements.cshtml
@{
    ViewBag.Title = "Aranžmani";
    Layout = "~/Views/Shared/_HomePageLayout.cshtml";
}

<h2>Aranžmani</h2>

@foreach (var arrangement in Model.SearchedArrangements)
{
    <div class="single_stuff wow fadeInDown">
        <div class="single_stuff_img"> <a href="#"><img src="~/images/stuff_img1.jpg" alt=""></a> </div>
        <div class="single_stuff_article">
            <div class="single_sarticle_inner">
                <a class="stuff_category" href="#">@arrangement.Destination.Country</a>
                <div class="stuff_article_inner">
                    <span class="stuff_date"><strong>@String.Format("{0:dd MMM}", arrangement.Arrangement.StartDate)</strong></span>
                    <h2><a href="#">@arrangement.Destination.PlaceName</a></h2>
                    <p>Cena: @arrangement.Arrangement.Price</p>
                </div>
            </div>
        </div>
    </div>
}

TravelAgency/TravelAgency/Views/Main/SearchDestinations.cshtml
@{
    ViewBag.Title = "Reultati pretrage";
    Layout = "~/Views/Shared/_HomePageLayout.cshtml";
}

<h2>Rezultati pretrage</h2>


@foreach (var destination in Model.SearchedDestinations)
{
    <div class="single_stuff wow fadeInDown">
        <div class="single_stuff_img"> <a href="pages/single.html"><img src="~/images/stuff_img1.jpg" alt=""></a> </div>
        <div class="single_stuff_article">
            <div class="single_sarticle_inner">
                <div class="stuff_article_inner">
                    <h2>
                        @{  string text = destination.Country != null ? destination.Country : " ";
                        }
                        @Html.ActionLink(text, "CountryArrangements", "Main", new { country = destination.Country, isLogged = Model.IsLogged }, null)
                    </h2>
                    <p>@destination.PlaceName</p>
                    <p>@destination.Description</p>
                </div>
            </div>
        </div>
    </div>
                            }